#!/bin/sh

# ┌─┐┌─┐┬─┐┌─┐┌─┐┌┐┌┌─┐┬ ┬┌─┐┌┬┐
# └─┐│  ├┬┘├┤ ├┤ │││└─┐├─┤│ │ │
# └─┘└─┘┴└─└─┘└─┘┘└┘└─┘┴ ┴└─┘ ┴

# author	Niraj
# github	niraj998

# ┌─┐┌─┐┌┐┌┌─┐┬┌─┐┬ ┬┬─┐┌─┐┌┬┐┬┌─┐┌┐┌┌─┐
# │  │ ││││├┤ ││ ┬│ │├┬┘├─┤ │ ││ ││││└─┐
# └─┘└─┘┘└┘└  ┴└─┘└─┘┴└─┴ ┴ ┴ ┴└─┘┘└┘└─┘

# Save Screenshots here
screenshotdir=~/Pictures/Screenshots
# file name
file=$screenshotdir/$(date '+%y%m%d-%H%M-%S').png
# icon for notification
icon=~/.config/rofi/screenshot/camera.png
# rofi config
roficonfig=~/.config/rofi/screenshot/config.rasi
#make sure you have directory
[ -d "$screenshotdir" ] || mkdir -pv "$screenshotdir"

# ┬─┐┌─┐┌─┐┬
# ├┬┘│ │├┤ │
# ┴└─└─┘└  ┴

# if you don't have the icons, go to Niraj's github and download them from their repository.

area=""
cwin=""
full=""
copy=""
save=""

rofiopt="$area\n$cwin\n$full"
rofi=$(printf "$rofiopt" | rofi -config $roficonfig -dmenu -i)
[ -z "$rofi" ] && exit
option="$save\n$copy"
saveopt=$(printf "$option" | rofi -config $roficonfig -dmenu -i)

case $rofi in
"$area")
  if [ "$saveopt" = "$copy" ]; then
    notify-send -i $icon --urgency low 'Select Area'
    grim -g "$(slurp)" - | wl-copy && notify-send -i $icon --urgency low 'Screenshot copied' || notify-send -i $icon 'failed to take screenshot'
  elif [ "$saveopt" = "$save" ]; then
    notify-send -i $icon --urgency low 'Select Area'
    grim -g "$(slurp)" "$file" && notify-send -i "$icon" --urgency low 'Screenshot Taken' || notify-send -i "$icon" 'failed to take screenshot'
  fi
  ;;
"$cwin")
  if [ "$saveopt" = "$copy" ]; then
    notify-send -i $icon --urgency low 'Select Window'
    swaymsg -t get_tree | jq -r '..|try(.nodes[])?|select(.type == "con" and .visible == true and .focused == true) | "grim -g \"\(.rect.x),\(.rect.y) \(.rect.width)x\(.rect.height)\" - | wl-copy"' | bash && notify-send -i $icon --urgency low 'Screenshot copied' || notify-send -i $icon 'failed to take screenshot'
  elif [ "$saveopt" = "$save" ]; then
    maim -u -m 5 -i "$(xdotool getactivewindow)" $file && notify-send -i $icon --urgency low 'Screenshot Taken' || notify-send -i $icon 'failed to take screenshot'
  fi
  ;;
"$full")
  if [ "$saveopt" = "$copy" ]; then
    sleep 2
    grim - | wl-copy && notify-send -i $icon --urgency low 'Screenshot copied' || notify-send -i $icon 'failed to take screenshot'
  elif [ "$saveopt" = "$save" ]; then
    sleep 2
    grim "$file" && notify-send -i $icon --urgency low 'Screenshot Taken' || notify-send -i $icon 'failed to take screenshot'
  fi
  ;;
esac
