#!/usr/bin/env bash

# ┌─┐┌─┐┬─┐┌─┐┌─┐┌┐┌┌─┐┬ ┬┌─┐┌┬┐
# └─┐│  ├┬┘├┤ ├┤ │││└─┐├─┤│ │ │
# └─┘└─┘┴└─└─┘└─┘┘└┘└─┘┴ ┴└─┘ ┴

# author	Niraj
# github	niraj998

# ┬─┐┌─┐┌─┐┬
# ├┬┘│ │├┤ │
# ┴└─└─┘└  ┴

# icon for notification
icon=~/.config/rofi/screen/screen.png
# rofi config
roficonfig=~/.config/rofi/screen/config.rasi

outputs=$(swaymsg -t get_outputs | jq -r '.[] | .name')
screen1=$(echo "$outputs" | head -n 1)
screen2=$(echo "$outputs" | tail -n 1)

Laptop=""
Monitor=""
Dualscreen=""
rofiopt="$Laptop\n$Monitor\n$Dualscreen"

rofi=$(printf "$rofiopt" | rofi -config $roficonfig -dmenu -i)

[ "$screen1" = "$screen2" ] && notify-send -i "$icon" "Second Screen is not connected" && exit
[ -z "$rofi" ] && exit

reload() {
  swaymsg reload
}

case $rofi in
$Laptop)
  swaymsg output "$screen1" enable res 1366x768 pos 0 0
  swaymsg output "$screen2" disable
  ;;
$Monitor)
  swaymsg output "$screen2" enable res 1920x1080 pos 0 0
  swaymsg output "$screen1" disable
  ;;

$Dualscreen)
  swaymsg output "$screen1" enable res 1366x768 pos 0 0
  swaymsg output "$screen2" enable res 1920x1080 pos 1366 0
  ;;
esac
