#!/bin/sh

swaylock \
  --screenshots \
  --clock \
  --indicator \
  --indicator-radius 100 \
  --indicator-thickness 7 \
  --effect-scale 0.5 --effect-blur 7x5 --effect-scale 2 \
  --effect-vignette 0.5:0.5 \
  \
  --ring-color bb00cc \
  --key-hl-color 880033 \
  --line-color 00000000 \
  --inside-color 00000088 \
  --separator-color 00000000 \
  \
  --text-wrong-color 880000bb \
  --inside-wrong-color ffffff22 \
  --inside-color 00000088 \
  \
  --text-ver-color bb00bbbb \
  --inside-ver-color ffffff22 \
  \
  --fade-in 0.2

